### ISSUE TITLE
Add flakyError and flakyFailure to the testcase.

### ISSUE THREAD

**Issue by dsimko** [dsimko/saatr#15]
`<testcase name="prepareHalt" classname="org.jboss.as.test.jbossts.crashrec.test.JPALrcoCrashRecoveryTestCase(jta)" time="81.013">
    <flakyError message="Transaction rolled back" type="javax.ejb.EJBTransactionRolledbackException"><![CDATA[javax.ejb.EJBTransactionRolledbackException: Transaction rolled back
    at org.jboss.as.ejb3.tx.CMTTxInterceptor.handleEndTransactionException(CMTTxInterceptor.java:137)
    at org.jboss.as.ejb3.tx.CMTTxInterceptor.endTransaction(CMTTxInterceptor.java:117)
    at org.jboss.as.ejb3.tx.CMTTxInterceptor.invokeInOurTx(CMTTxInterceptor.java:279)
    at org.jboss.as.ejb3.tx.CMTTxInterceptor.required(CMTTxInterceptor.java:327)
    at org.jboss.as.ejb3.tx.CMTTxInterceptor.processInvocation(CMTTxInterceptor.java:239)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.as.ejb3.remote.EJBRemoteTransactionPropagatingInterceptor.processInvocation(EJBRemoteTransactionPropagatingInterceptor.java:79)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.as.ejb3.component.interceptors.CurrentInvocationContextInterceptor.processInvocation(CurrentInvocationContextInterceptor.java:41)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.as.ejb3.component.invocationmetrics.WaitTimeInterceptor.processInvocation(WaitTimeInterceptor.java:47)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.as.ejb3.security.SecurityContextInterceptor.processInvocation(SecurityContextInterceptor.java:100)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at org.jboss.as.ejb3.deployment.processors.StartupAwaitInterceptor.processInvocation(StartupAwaitInterceptor.java:22)
    at org.jboss.invocation.InterceptorContext.proceed(InterceptorContext.java:340)
    at ...
]]>
      <system-out><![CDATA[02:01:11,226 INFO  [org.jboss.as.test.jbossts.junit.JUnitRuleProcessAnnotation] (main) JUnitRuleProcessAnnotation evaluate()
02:01:11,226 INFO  [org.jboss.as.test.jbossts.junit.JUnitRuleIgnoreIfNameContained] (main) JUnitRuleIgnoreIfNameContained evaluate()
...
]]></system-out>
    </flakyError>
    <flakyFailure message="JBoss log parsed file /home/hudson/hudson_workspace/workspace/eap-71-jbossts-crashrec-tests-jpa-dsimko/ec408930/eap-tests-transactions/jbossts/target/jbossas-jbossts/standalone/log/JPALrcoCrashRecoveryTestCase_prepareHalt_jta_server.log contains not expected string ERROR on line 4219 with text &apos;2016-08-29 02:18:34,575 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-6) IO Error: Connection timed out&apos;" type="java.lang.AssertionError">java.lang.AssertionError: JBoss log parsed file /home/hudson/hudson_workspace/workspace/eap-71-jbossts-crashrec-tests-jpa-dsimko/ec408930/eap-tests-transactions/jbossts/target/jbossas-jbossts/standalone/log/JPALrcoCrashRecoveryTestCase_prepareHalt_jta_server.log contains not expected string ERROR on line 4219 with text '2016-08-29 02:18:34,575 ERROR [org.hibernate.engine.jdbc.spi.SqlExceptionHelper] (default task-6) IO Error: Connection timed out'
    at org.junit.Assert.fail(Assert.java:88)
    at org.jboss.as.test.jbossts.arquillian.logparser.JBossLogParserProcessor.readAndParse(JBossLogParserProcessor.java:207)
    at org.jboss.as.test.jbossts.arquillian.logparser.JBossLogParserProcessor.handleAfterTest(JBossLogParserProcessor.java:163)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:498)
    at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:94)
    at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:99)
    at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:81)
    at ...
</flakyFailure>
  </testcase>
`

**Comment by dsimko** [comment]
done
